# Generated by Django 5.2.7 on 2025-10-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='ai_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reflection',
            name='prompt_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='reflection_type',
            field=models.CharField(choices=[('gratitude', '😊 Gratitude'), ('emotion', '🎭 Émotions'), ('cycle', '🌙 Cycle & Humeur'), ('mindfulness', '🧘 Pleine Conscience')], default='emotion', max_length=20),
        ),
    ]
