# Generated by Django 5.2.7 on 2025-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageentry',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AudioEntry',
        ),
    ]
