# Generated by Django 5.2.4 on 2025-10-31 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_planning', '0002_alter_aiinsight_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('task_summary', 'Task Summary'), ('project_analysis', 'Project Analysis'), ('goal_action_plan', 'Goal Action Plan'), ('productivity_insights', 'Productivity Insights'), ('task_breakdown', 'Task Breakdown')], max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('response_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'response_type', 'content_type', 'object_id')},
            },
        ),
    ]
