# Generated by Django 5.2.4 on 2025-10-29 22:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('weekly', 'Weekly Analysis'), ('monthly', 'Monthly Analysis'), ('correlation', 'Mood-Habit Correlation'), ('pattern', 'Pattern Analysis'), ('recommendation', 'Recommendation')], help_text='Type of insight generated', max_length=20)),
                ('content', models.TextField(help_text='The AI-generated insight content')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data_period_start', models.DateField(help_text='Start date of the data period analyzed')),
                ('data_period_end', models.DateField(help_text='End date of the data period analyzed')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this insight has been archived')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the habit', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the habit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this habit is currently being tracked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the habit log')),
                ('completed', models.BooleanField(default=False, help_text='Whether the habit was completed on this date')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the habit completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to='mood_tracker.habit')),
            ],
            options={
                'verbose_name': 'Habit Log',
                'verbose_name_plural': 'Habit Logs',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')], help_text='Mood level on a scale of 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mood_label', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('energetic', 'Energetic'), ('tired', 'Tired'), ('focused', 'Focused'), ('stressed', 'Stressed'), ('content', 'Content'), ('frustrated', 'Frustrated')], help_text='Descriptive label for the mood', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the mood')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the mood entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
