# Generated by Django 5.2.4 on 2025-10-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_alter_mediafile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='transcription',
            field=models.TextField(blank=True, help_text='Auto-generated transcription for audio files', null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcription_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score of transcription', null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of speech-to-text processing', max_length=20),
        ),
    ]
